// Guías organizadas por lugar a partir de las notas de viaje del autor.
// Los datos de visita enlazan a fuentes oficiales porque pueden cambiar.
const japanCountry = {
  slug: 'japon', name: 'Japón', kicker: 'Tradición y energía urbana', flag: 'JP',
  intro: 'Templos, barrios llenos de vida y paisajes que invitan a mirar con atención. Explora cada lugar sin seguir un itinerario fijo.',
  image: 'assets/kioto.jpg', cities: ['kioto','nara','uji','osaka','miyajima','himeji','tokio','kamakura']
};

const japanCities = [
  {slug:'kioto',country:'japon',name:'Kioto',region:'Kansai',image:'assets/kioto.jpg',eyebrow:'Templos, jardines y calles antiguas',intro:'La antigua capital conserva santuarios, jardines y barrios históricos. Entre Fushimi Inari, Higashiyama y Arashiyama hay mucho que descubrir sin necesidad de seguir una ruta cerrada.',days:'3–5 días',best:'Primavera y otoño',move:'Tren + autobús + a pie',lat:35.0116,lon:135.7681,tips:[['Sal temprano','Los templos más conocidos se disfrutan mejor a primera hora.'],['Agrupa por zonas','Higashiyama, el norte y Arashiyama requieren desplazamientos distintos.'],['Respeta el barrio','En Gion y otras calles residenciales, atiende a la señalización y evita bloquear el paso.']]},
  {slug:'nara',country:'japon',name:'Nara',region:'Kansai',image:'assets/nara.jpg',eyebrow:'El Gran Buda y los ciervos del parque',intro:'Nara fue una de las primeras capitales de Japón. Sus grandes templos se encuentran junto a un parque donde los ciervos forman parte del paisaje.',days:'1–2 días',best:'Primavera y otoño',move:'A pie',lat:34.6851,lon:135.8048,tips:[['Respeta a los ciervos','Son animales salvajes; aliméntalos solo con las galletas autorizadas y guarda papeles y comida.'],['Camina entre templos','El parque conecta varias visitas importantes.'],['Reserva tiempo','El recinto de Tōdai-ji merece algo más que una foto rápida.']]},
  {slug:'uji',country:'japon',name:'Uji',region:'Prefectura de Kioto',image:'assets/uji.jpg',eyebrow:'Té, río y patrimonio Heian',intro:'A orillas del río Uji, esta pequeña ciudad reúne casas de té, calles tranquilas y el célebre Salón del Fénix de Byōdō-in.',days:'Medio día–1 día',best:'Primavera y otoño',move:'A pie',lat:34.8845,lon:135.7997,tips:[['Prueba el té local','Uji es una de las zonas más conocidas por su té verde.'],['Cruza el río','Las dos orillas ofrecen paseos y vistas diferentes.'],['Consulta el Salón del Fénix','La visita interior puede tener cupo y horario propios.']]},
  {slug:'osaka',country:'japon',name:'Osaka',region:'Kansai',image:'assets/osaka.jpg',eyebrow:'Neones, castillo y cultura de calle',intro:'Osaka mezcla el legado de su castillo con barrios comerciales muy vivos. Dōtonbori y Namba muestran su cara más luminosa.',days:'2–3 días',best:'Primavera y otoño',move:'Metro + a pie',lat:34.6937,lon:135.5023,tips:[['Ve con hambre','Dōtonbori es una zona popular para probar comida callejera.'],['Distingue parque y museo','Pasear por el parque del castillo es diferente a entrar en el museo de la torre.'],['Explora a pie','Namba, Nipponbashi y Dōtonbori se disfrutan caminando.']]},
  {slug:'miyajima',country:'japon',name:'Miyajima',region:'Prefectura de Hiroshima',image:'assets/miyajima.jpg',eyebrow:'La isla del torii sobre el mar',intro:'La isla de Itsukushima combina santuarios, montaña y el ritmo de las mareas. Su gran torii cambia de aspecto a lo largo del día.',days:'1 día',best:'Primavera y otoño',move:'Ferri + a pie',lat:34.2959,lon:132.3199,tips:[['Mira las mareas','La experiencia del torii cambia mucho con marea alta y baja.'],['Cuida a los ciervos','No les des comida ni dejes bolsas a su alcance.'],['Atiende al último ferri','Consulta los horarios de regreso antes de alejarte del muelle.']]},
  {slug:'himeji',country:'japon',name:'Himeji',region:'Prefectura de Hyōgo',image:'assets/himeji.jpg',eyebrow:'Un castillo blanco que parece flotar',intro:'Himeji es conocido por uno de los castillos históricos mejor conservados de Japón, rodeado por un complejo sistema de puertas y murallas.',days:'Medio día–1 día',best:'Primavera y otoño',move:'A pie',lat:34.8151,lon:134.6853,tips:[['Lleva calcetines','En el interior del castillo se camina sin zapatos.'],['Sube con calma','Hay escaleras de madera empinadas.'],['Añade el jardín','Kōko-en está cerca del castillo y se puede visitar por separado.']]},
  {slug:'tokio',country:'japon',name:'Tokio',region:'Kantō',image:'assets/tokio.jpg',eyebrow:'Barrios, templos y mil maneras de mirar',intro:'Tokio cambia de carácter en cada barrio: Asakusa, Ueno, Akihabara, Shibuya, Harajuku y Shinjuku ofrecen mundos distintos dentro de la misma ciudad.',days:'4–6 días',best:'Primavera y otoño',move:'Tren + metro',lat:35.6762,lon:139.6503,tips:[['Elige barrios cercanos','Los trayectos pueden llevar más tiempo de lo que parecen en el mapa.'],['Lleva una tarjeta de transporte','Facilita los cambios entre redes de tren y metro.'],['Alterna ritmos','Combina calles concurridas con parques y santuarios.']]},
  {slug:'kamakura',country:'japon',name:'Kamakura',region:'Prefectura de Kanagawa',image:'assets/kamakura.jpg',eyebrow:'El Gran Buda junto al mar',intro:'Antigua sede del poder samurái, Kamakura reúne templos, santuarios y senderos entre colinas a poca distancia de la costa.',days:'1 día',best:'Primavera y otoño',move:'Tren local + a pie',lat:35.3192,lon:139.5467,tips:[['Camina entre visitas','El Gran Buda y Hase-dera están relativamente cerca.'],['Mira el tiempo','Los senderos y jardines se disfrutan más con buen tiempo.'],['Deja margen para volver','La zona recibe muchas excursiones de un día desde Tokio.']]}
];

const japanPlaces = [
  {slug:'fushimi-inari',city:'kioto',name:'Fushimi Inari Taisha',category:'Santuario',image:'assets/fushimi-inari.jpg',lead:'Un camino de miles de torii rojos que asciende por el monte Inari.',story:'Este santuario está dedicado a Inari, deidad vinculada al arroz y la prosperidad. Las puertas torii son donaciones de particulares y empresas; el recorrido conduce desde los edificios principales hasta senderos de la montaña.',curiosity:'Si miras la parte trasera de muchos torii, verás el nombre de quien los donó y la fecha.',duration:'1,5–3 horas',hours:'Los caminos exteriores se pueden recorrer a cualquier hora; oficinas y edificios tienen horarios propios.',price:'Acceso al recinto gratuito',ticket:'No necesitas entrada para recorrer los torii.',official:'https://inari.jp/en/',hoursSource:'https://inari.jp/en/',lat:34.9671,lon:135.7727,tip:'Sube más allá de los primeros tramos si buscas un paseo con menos gente.'},
  {slug:'kiyomizu-dera',city:'kioto',name:'Kiyomizu-dera',category:'Templo',image:'assets/kioto.jpg',lead:'Un templo levantado sobre la ladera, con vistas abiertas a Kioto.',story:'Fundado en el siglo VIII, Kiyomizu-dera toma su nombre de la cascada Otowa. Su gran terraza de madera y los distintos edificios del recinto muestran siglos de reconstrucciones y vida religiosa.',curiosity:'La terraza principal se sostiene con una compleja estructura de madera sin clavos en sus uniones tradicionales.',duration:'1,5–2 horas',hours:'Abre a las 6:00; el cierre cambia según la fecha y puede ampliarse en visitas nocturnas.',price:'Consulta la tarifa actual en la web oficial',ticket:'La entrada se adquiere para acceder a la zona principal del templo.',official:'https://www.kiyomizudera.or.jp/en/',hoursSource:'https://www.kiyomizudera.or.jp/en/location/',lat:34.9948,lon:135.785,tip:'Llega por las calles de Sannenzaka y Ninenzaka y reserva tiempo para la cascada Otowa.'},
  {slug:'kinkaku-ji',city:'kioto',name:'Kinkaku-ji',category:'Templo y jardín',image:'assets/kinkakuji.jpg',lead:'El Pabellón Dorado reflejado en el estanque de un jardín zen.',story:'El edificio fue residencia de un shōgun antes de convertirse en templo budista. El pabellón actual reconstruye el original y forma parte de un jardín pensado para descubrirse caminando.',curiosity:'Sus plantas superiores están recubiertas con pan de oro; cada nivel presenta un estilo arquitectónico diferente.',duration:'45–75 min',hours:'Generalmente 9:00–17:00; confirma cambios y cierres especiales.',price:'Consulta la tarifa actual en la web oficial',ticket:'La entrada se compra en el acceso, según la información oficial.',official:'https://www.shokoku-ji.jp/en/kinkakuji/',hoursSource:'https://www.shokoku-ji.jp/en/kinkakuji/access/',lat:35.0394,lon:135.7292,tip:'El recorrido es de sentido único; detente junto al estanque para apreciar el reflejo.'},
  {slug:'arashiyama',city:'kioto',name:'Bosque de bambú de Arashiyama',category:'Naturaleza',image:'assets/arashiyama.jpg',lead:'Un sendero entre bambúes que revela otra textura de Kioto.',story:'El bosque de Sagano atraviesa una zona de Arashiyama vinculada históricamente a villas, templos y paseos junto al río. Hoy es uno de los paisajes más fotografiados de la ciudad.',curiosity:'El sonido del bambú al moverse con el viento es una parte tan característica de la visita como la imagen.',duration:'30–60 min',hours:'Sendero exterior de acceso libre; los templos cercanos tienen sus propios horarios.',price:'Acceso al sendero gratuito',ticket:'No hace falta reservar para pasear por el bosque.',official:'https://kyoto.travel/en/areas/saga-arashiyama/',hoursSource:'https://kyoto.travel/en/areas/saga-arashiyama/',lat:35.017,lon:135.6713,tip:'Ve temprano y combina el paseo con el río y los templos del barrio.'},
  {slug:'todai-ji',city:'nara',name:'Tōdai-ji',category:'Templo',image:'assets/nara.jpg',lead:'El gran templo de Nara y su monumental Buda de bronce.',story:'Fundado en el siglo VIII, Tōdai-ji fue un centro del budismo estatal. El Gran Salón del Buda alberga una de las imágenes budistas más conocidas de Japón y sigue siendo un lugar de culto.',curiosity:'El enorme salón actual es una reconstrucción más pequeña que el edificio original.',duration:'1–1,5 horas',hours:'El horario del Gran Salón cambia según la estación.',price:'Entrada de pago; consulta la tarifa oficial',ticket:'Compra la entrada en la taquilla del recinto.',official:'https://www.todaiji.or.jp/en/',hoursSource:'https://www.todaiji.or.jp/en/',lat:34.689,lon:135.8398,tip:'Recorre también los caminos del parque y mantén la comida lejos de los ciervos.'},
  {slug:'byodo-in',city:'uji',name:'Byōdō-in',category:'Templo',image:'assets/uji.jpg',lead:'El Salón del Fénix junto al estanque, icono de la era Heian.',story:'La antigua villa aristocrática se convirtió en templo en el siglo XI. Su Salón del Fénix evoca la Tierra Pura budista y es una de las imágenes más reconocibles del patrimonio japonés.',curiosity:'El Salón del Fénix aparece representado en la moneda japonesa de 10 yenes.',duration:'1–1,5 horas',hours:'Jardín, museo e interior del Salón del Fénix tienen horarios diferentes.',price:'Entrada de pago; el interior del Salón del Fénix lleva suplemento',ticket:'Consulta el acceso al salón interior al llegar: las plazas pueden ser limitadas.',official:'https://www.byodoin.or.jp/en/guide/',hoursSource:'https://www.byodoin.or.jp/en/guide/',lat:34.8894,lon:135.8077,tip:'Mira el reflejo del salón en el estanque y deja tiempo para el museo.'},
  {slug:'castillo-de-osaka',city:'osaka',name:'Castillo de Osaka',category:'Castillo y museo',image:'assets/castillo-osaka.jpg',lead:'La gran silueta blanca y verde que recuerda la historia de Osaka.',story:'Toyotomi Hideyoshi impulsó el castillo en el siglo XVI. La torre actual, reconstruida en 1931, alberga un museo dedicado a la historia del castillo y de su época.',curiosity:'El parque conserva fosos y murallas; la visita exterior y la entrada al museo son experiencias distintas.',duration:'1,5–2 horas',hours:'Museo normalmente 9:00–18:00; última entrada media hora antes.',price:'1.200 ¥ adulto para el museo (referencia 2026)',ticket:'Consulta las opciones de entrada en la web oficial del museo.',official:'https://www.osakacastle.net/',hoursSource:'https://www.osakacastle.net/guide/',lat:34.6873,lon:135.5262,tip:'Da una vuelta por el parque antes o después de subir a la torre.'},
  {slug:'dotonbori',city:'osaka',name:'Dōtonbori',category:'Barrio',image:'assets/dotonbori.jpg',lead:'Neones, canales y comida callejera en el corazón más animado de Osaka.',story:'La zona se desarrolló alrededor de un canal del siglo XVII y creció como distrito de teatros y entretenimiento. Hoy sus enormes rótulos y restaurantes forman una de las escenas urbanas más famosas de Japón.',curiosity:'El corredor del canal ofrece una perspectiva distinta de los carteles luminosos y puentes.',duration:'1–2 horas',hours:'Calles públicas accesibles a cualquier hora; cada local tiene su propio horario.',price:'Paseo gratuito',ticket:'No se necesita entrada para recorrer el barrio.',official:'https://osaka-info.jp/en/area/dotonbori/',hoursSource:'https://osaka-info.jp/en/area/dotonbori/',lat:34.6687,lon:135.5015,tip:'Acércate al anochecer para ver los carteles iluminados.'},
  {slug:'itsukushima',city:'miyajima',name:'Santuario de Itsukushima',category:'Santuario',image:'assets/miyajima.jpg',lead:'Pasarelas rojas y un gran torii que cambia con la marea.',story:'El santuario se extendió sobre el mar durante la era Heian y mantiene una estrecha relación con la isla y el agua. Sus edificios están conectados por pasarelas y el torii marca el acceso simbólico desde la bahía.',curiosity:'Con marea alta parece flotar; con marea baja se puede apreciar mejor el suelo que rodea el torii.',duration:'45–75 min',hours:'El cierre varía durante el año; consulta la tabla oficial antes del ferri.',price:'300 ¥ adulto (santuario, tarifa publicada)',ticket:'Compra la entrada en el acceso; el ferri se paga aparte.',official:'https://itsukushimajinja.jp/en/',hoursSource:'https://itsukushimajinja.jp/en/admission.html',lat:34.2959,lon:132.3199,tip:'Consulta la marea del día para elegir el ambiente que prefieres.'},
  {slug:'castillo-de-himeji',city:'himeji',name:'Castillo de Himeji',category:'Castillo',image:'assets/himeji.jpg',lead:'Una fortaleza blanca con un laberinto de patios y puertas.',story:'El castillo tomó su forma actual a comienzos del siglo XVII. Su torre principal, sus defensas y los recorridos interiores permiten entender la arquitectura militar del Japón feudal.',curiosity:'Su apodo, Castillo de la Garza Blanca, alude al aspecto claro y elegante de sus tejados.',duration:'1,5–2,5 horas',hours:'Horario y última entrada variables según temporada y eventos.',price:'Entrada de pago; consulta la tarifa oficial',ticket:'Las entradas se venden por los canales indicados en la web oficial.',official:'https://www.himejicastle.jp/en/',hoursSource:'https://www.himejicastle.jp/en/',lat:34.8394,lon:134.6939,tip:'Hay escaleras estrechas y empinadas en la torre; sube sin prisa.'},
  {slug:'senso-ji',city:'tokio',name:'Sensō-ji',category:'Templo',image:'assets/sensoji.jpg',lead:'La gran puerta de Asakusa y un templo ligado a los orígenes de Tokio.',story:'Sensō-ji es uno de los templos más antiguos de Tokio. La puerta Kaminarimon conduce por la calle Nakamise hasta el salón principal, un recorrido que une comercio popular y tradición religiosa.',curiosity:'La gran linterna de Kaminarimon es uno de los símbolos más fotografiados de Asakusa.',duration:'45–90 min',hours:'El recinto exterior es accesible a cualquier hora; el salón principal tiene horario limitado.',price:'Acceso general gratuito',ticket:'No se necesita entrada para la visita general.',official:'https://www.senso-ji.jp/english/',hoursSource:'https://www.senso-ji.jp/english/',lat:35.7148,lon:139.7967,tip:'Pasea también por las calles laterales de Asakusa después de Nakamise.'},
  {slug:'meiji-jingu',city:'tokio',name:'Meiji Jingū',category:'Santuario',image:'assets/meiji.jpg',lead:'Un santuario entre árboles a pocos pasos de Harajuku.',story:'Dedicado al emperador Meiji y a la emperatriz Shōken, el santuario se inauguró en 1920. Los amplios caminos arbolados separan la intensidad de la ciudad de un espacio de recogimiento.',curiosity:'En el camino verás grandes barriles de sake ofrecidos al santuario.',duration:'1–1,5 horas',hours:'Abre al amanecer y cierra al atardecer; el horario exacto cambia cada mes.',price:'Acceso al santuario gratuito; jardín y museo pueden tener tarifa',ticket:'No necesitas entrada para el recinto principal.',official:'https://www.meijijingu.or.jp/en/',hoursSource:'https://www.meijijingu.or.jp/en/',lat:35.6764,lon:139.6993,tip:'Combina la visita con Yoyogi y Harajuku, pero deja un momento de calma dentro del bosque.'},
  {slug:'gran-buda',city:'kamakura',name:'Gran Buda de Kamakura',category:'Templo',image:'assets/kamakura.jpg',lead:'Una gran figura de bronce al aire libre en Kōtoku-in.',story:'La estatua de Amida Buda se realizó en el siglo XIII. Al desaparecer el edificio que la cubría, quedó expuesta al cielo y se convirtió en el icono más reconocible de Kamakura.',curiosity:'En determinados horarios es posible acceder al interior de la estatua mediante una entrada adicional.',duration:'30–60 min',hours:'El recinto tiene horarios estacionales; comprueba la apertura antes de ir.',price:'Entrada de pago; consulta la tarifa oficial',ticket:'Se adquiere en el acceso al templo.',official:'https://www.kotoku-in.jp/en/',hoursSource:'https://www.kotoku-in.jp/en/',lat:35.3167,lon:139.5357,tip:'Hase-dera queda cerca y permite completar el paseo por esta zona.'}
];

// Las fichas ampliadas viven en data/japon/, agrupadas por ciudad.
const japanCityImage = Object.fromEntries(japanCities.map(city => [city.slug, city.image]));
const japanPlaceImages = new Set([
  'nishiki','pontocho','gion-miyagawacho','yasaka-jinja','sannenzaka-ninenzaka','ginkaku-ji','nanzen-ji','castillo-nijo','ryoan-ji','ninna-ji','chion-in-maruyama','heian-jingu',
  'parque-nara','kasuga-taisha','kofuku-ji','ukimido','ujigami-jinja','calle-te-uji',
  'momijidani','monte-misen','senjokaku','jardin-koko-en',
  'shinsekai','nipponbashi','shitenno-ji','isshin-ji','namba','asakusa'
]);
function addJapanPlace(city, slug, name, category, lat, lon, lead, story, curiosity, official, duration = '45–90 min', hours = 'Consulta los horarios de cada recinto en la web oficial.', price = 'Consulta la tarifa actual', ticket = 'Consulta la venta y las reservas en la web oficial.', tip = 'Comprueba el acceso antes de desplazarte.') {
  const image = japanPlaceImages.has(slug) ? `assets/japon-${slug}.jpg` : japanCityImage[city];
  japanPlaces.push({slug, city, name, category, lat, lon, image, lead, story, curiosity, official, hoursSource:official, duration, hours, price, ticket, tip});
}
function addJapanHistory(entries) {
  for (const place of japanPlaces) if (entries[place.slug]) place.history = entries[place.slug];
}
